version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_voll_med
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: voll_med
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: